---
title: "HW 1"
author: "Div Dasani"
date: "October 9, 2018"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Problem 1.1
###let $h(x) = \frac{x}{(1+x^2)^2}$
###$\int_1^3 h(x) \; dx = 2\int_1^3 \frac{1}{2}h(x) \; dx = E_{f}[2h(x)]$ where $f$~$U(1,3)$
```{r p1.1}
f <- function(x) {
  2*x/((1+x^2)^2);
}
n <- 100000
x <- runif(n, min=1, max=3)
mean(f(x))
```

##Problem 1.2
###$N(0,\sqrt{\frac{1}{2}})$=$\frac{1}{\sqrt{\pi}}e^{-x^2}$
###$\int_{-\infty}^{\infty} x^2e^{-x^2} \; dx = \sqrt{\pi}\int_{-\infty}^{\infty} \frac{1}{\sqrt{\pi}}e^{-x^2}x^2 \; dx = E_{f}[\sqrt{\pi}x^2]$ where $f$~$N(0,\sqrt{\frac{1}{2}})$
```{r p1.2}
f <- function(x) {
  sqrt(pi)*x^2;
}
n <- 100000
x <- rnorm(n,0,sqrt(1/2))
mean(x)
mean(f(x))
```

##Problem 1.3
###let $h(x) = |x-y|$
###$\int_{-1}^1\int_{-1}^1 h(x) \;\; dxdy = (2*2)\int_{-1}^1\int_{-1}^1(\frac{1}{2}*\frac{1}{2})h(x) \;\; dxdy = E_{f}[4h(x)]$ where $f$~$U(-1,1)$
```{r p1.3}
f <- function(x,y) {
  4*abs(x-y);
}
n <- 100000
x <- runif(n,min=-1, max=1)
y <- runif(n,min=-1, max =1)
mean(f(x,y))
```

##Problem 2.1
```{r p2.1}
f <- function(x,e) {
  9+3*log(x) + e
}
n <- 100000
x <- rlnorm(n)
x <- replace(x,x==0,0.000001)
e <- rnorm(n)
exp(mean(f(x,e)))/mean(x)
```